# Generated by Django 3.1.1 on 2020-09-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200925_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=1, related_name='postByTags', to='posts.Tag'),
        ),
    ]
