# Generated by Django 3.1.1 on 2020-09-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_slider_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slider_post',
        ),
    ]
